/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AOuLini extends PLini
{
    private PLini _lini_;
    private PLsoma _lsoma_;
    private PLtermo _ltermo_;

    public AOuLini()
    {
        // Constructor
    }

    public AOuLini(
        @SuppressWarnings("hiding") PLini _lini_,
        @SuppressWarnings("hiding") PLsoma _lsoma_,
        @SuppressWarnings("hiding") PLtermo _ltermo_)
    {
        // Constructor
        setLini(_lini_);

        setLsoma(_lsoma_);

        setLtermo(_ltermo_);

    }

    @Override
    public Object clone()
    {
        return new AOuLini(
            cloneNode(this._lini_),
            cloneNode(this._lsoma_),
            cloneNode(this._ltermo_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOuLini(this);
    }

    public PLini getLini()
    {
        return this._lini_;
    }

    public void setLini(PLini node)
    {
        if(this._lini_ != null)
        {
            this._lini_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lini_ = node;
    }

    public PLsoma getLsoma()
    {
        return this._lsoma_;
    }

    public void setLsoma(PLsoma node)
    {
        if(this._lsoma_ != null)
        {
            this._lsoma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lsoma_ = node;
    }

    public PLtermo getLtermo()
    {
        return this._ltermo_;
    }

    public void setLtermo(PLtermo node)
    {
        if(this._ltermo_ != null)
        {
            this._ltermo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ltermo_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._lini_)
            + toString(this._lsoma_)
            + toString(this._ltermo_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._lini_ == child)
        {
            this._lini_ = null;
            return;
        }

        if(this._lsoma_ == child)
        {
            this._lsoma_ = null;
            return;
        }

        if(this._ltermo_ == child)
        {
            this._ltermo_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._lini_ == oldChild)
        {
            setLini((PLini) newChild);
            return;
        }

        if(this._lsoma_ == oldChild)
        {
            setLsoma((PLsoma) newChild);
            return;
        }

        if(this._ltermo_ == oldChild)
        {
            setLtermo((PLtermo) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
