/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ALini extends PLini
{
    private PLtermo _ltermo_;

    public ALini()
    {
        // Constructor
    }

    public ALini(
        @SuppressWarnings("hiding") PLtermo _ltermo_)
    {
        // Constructor
        setLtermo(_ltermo_);

    }

    @Override
    public Object clone()
    {
        return new ALini(
            cloneNode(this._ltermo_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALini(this);
    }

    public PLtermo getLtermo()
    {
        return this._ltermo_;
    }

    public void setLtermo(PLtermo node)
    {
        if(this._ltermo_ != null)
        {
            this._ltermo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ltermo_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ltermo_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ltermo_ == child)
        {
            this._ltermo_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ltermo_ == oldChild)
        {
            setLtermo((PLtermo) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
