/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AExpLogica extends PExpLogica
{
    private PLexp _lexp_;

    public AExpLogica()
    {
        // Constructor
    }

    public AExpLogica(
        @SuppressWarnings("hiding") PLexp _lexp_)
    {
        // Constructor
        setLexp(_lexp_);

    }

    @Override
    public Object clone()
    {
        return new AExpLogica(
            cloneNode(this._lexp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpLogica(this);
    }

    public PLexp getLexp()
    {
        return this._lexp_;
    }

    public void setLexp(PLexp node)
    {
        if(this._lexp_ != null)
        {
            this._lexp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lexp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._lexp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._lexp_ == child)
        {
            this._lexp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._lexp_ == oldChild)
        {
            setLexp((PLexp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
