/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AIgualLexp extends PLexp
{
    private PLexp _lexp_;
    private PLcomp _lcomp_;
    private PLini _lini_;

    public AIgualLexp()
    {
        // Constructor
    }

    public AIgualLexp(
        @SuppressWarnings("hiding") PLexp _lexp_,
        @SuppressWarnings("hiding") PLcomp _lcomp_,
        @SuppressWarnings("hiding") PLini _lini_)
    {
        // Constructor
        setLexp(_lexp_);

        setLcomp(_lcomp_);

        setLini(_lini_);

    }

    @Override
    public Object clone()
    {
        return new AIgualLexp(
            cloneNode(this._lexp_),
            cloneNode(this._lcomp_),
            cloneNode(this._lini_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIgualLexp(this);
    }

    public PLexp getLexp()
    {
        return this._lexp_;
    }

    public void setLexp(PLexp node)
    {
        if(this._lexp_ != null)
        {
            this._lexp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lexp_ = node;
    }

    public PLcomp getLcomp()
    {
        return this._lcomp_;
    }

    public void setLcomp(PLcomp node)
    {
        if(this._lcomp_ != null)
        {
            this._lcomp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lcomp_ = node;
    }

    public PLini getLini()
    {
        return this._lini_;
    }

    public void setLini(PLini node)
    {
        if(this._lini_ != null)
        {
            this._lini_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lini_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._lexp_)
            + toString(this._lcomp_)
            + toString(this._lini_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._lexp_ == child)
        {
            this._lexp_ = null;
            return;
        }

        if(this._lcomp_ == child)
        {
            this._lcomp_ = null;
            return;
        }

        if(this._lini_ == child)
        {
            this._lini_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._lexp_ == oldChild)
        {
            setLexp((PLexp) newChild);
            return;
        }

        if(this._lcomp_ == oldChild)
        {
            setLcomp((PLcomp) newChild);
            return;
        }

        if(this._lini_ == oldChild)
        {
            setLini((PLini) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
