/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ANotExpLogica extends PExpLogica
{
    private TNao _nao_;
    private PTermoLogica _termoLogica_;

    public ANotExpLogica()
    {
        // Constructor
    }

    public ANotExpLogica(
        @SuppressWarnings("hiding") TNao _nao_,
        @SuppressWarnings("hiding") PTermoLogica _termoLogica_)
    {
        // Constructor
        setNao(_nao_);

        setTermoLogica(_termoLogica_);

    }

    @Override
    public Object clone()
    {
        return new ANotExpLogica(
            cloneNode(this._nao_),
            cloneNode(this._termoLogica_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANotExpLogica(this);
    }

    public TNao getNao()
    {
        return this._nao_;
    }

    public void setNao(TNao node)
    {
        if(this._nao_ != null)
        {
            this._nao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nao_ = node;
    }

    public PTermoLogica getTermoLogica()
    {
        return this._termoLogica_;
    }

    public void setTermoLogica(PTermoLogica node)
    {
        if(this._termoLogica_ != null)
        {
            this._termoLogica_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._termoLogica_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._nao_)
            + toString(this._termoLogica_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._nao_ == child)
        {
            this._nao_ = null;
            return;
        }

        if(this._termoLogica_ == child)
        {
            this._termoLogica_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._nao_ == oldChild)
        {
            setNao((TNao) newChild);
            return;
        }

        if(this._termoLogica_ == oldChild)
        {
            setTermoLogica((PTermoLogica) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
