/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AExppLogica extends PExppLogica
{
    private PExppLogica _exppLogica_;
    private PSimboloLogica _simboloLogica_;
    private PTermoLogica _termoLogica_;

    public AExppLogica()
    {
        // Constructor
    }

    public AExppLogica(
        @SuppressWarnings("hiding") PExppLogica _exppLogica_,
        @SuppressWarnings("hiding") PSimboloLogica _simboloLogica_,
        @SuppressWarnings("hiding") PTermoLogica _termoLogica_)
    {
        // Constructor
        setExppLogica(_exppLogica_);

        setSimboloLogica(_simboloLogica_);

        setTermoLogica(_termoLogica_);

    }

    @Override
    public Object clone()
    {
        return new AExppLogica(
            cloneNode(this._exppLogica_),
            cloneNode(this._simboloLogica_),
            cloneNode(this._termoLogica_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExppLogica(this);
    }

    public PExppLogica getExppLogica()
    {
        return this._exppLogica_;
    }

    public void setExppLogica(PExppLogica node)
    {
        if(this._exppLogica_ != null)
        {
            this._exppLogica_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exppLogica_ = node;
    }

    public PSimboloLogica getSimboloLogica()
    {
        return this._simboloLogica_;
    }

    public void setSimboloLogica(PSimboloLogica node)
    {
        if(this._simboloLogica_ != null)
        {
            this._simboloLogica_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._simboloLogica_ = node;
    }

    public PTermoLogica getTermoLogica()
    {
        return this._termoLogica_;
    }

    public void setTermoLogica(PTermoLogica node)
    {
        if(this._termoLogica_ != null)
        {
            this._termoLogica_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._termoLogica_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exppLogica_)
            + toString(this._simboloLogica_)
            + toString(this._termoLogica_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exppLogica_ == child)
        {
            this._exppLogica_ = null;
            return;
        }

        if(this._simboloLogica_ == child)
        {
            this._simboloLogica_ = null;
            return;
        }

        if(this._termoLogica_ == child)
        {
            this._termoLogica_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exppLogica_ == oldChild)
        {
            setExppLogica((PExppLogica) newChild);
            return;
        }

        if(this._simboloLogica_ == oldChild)
        {
            setSimboloLogica((PSimboloLogica) newChild);
            return;
        }

        if(this._termoLogica_ == oldChild)
        {
            setTermoLogica((PTermoLogica) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
