/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ATermoExppLogica extends PExppLogica
{
    private PTermoLogica _termoLogica_;

    public ATermoExppLogica()
    {
        // Constructor
    }

    public ATermoExppLogica(
        @SuppressWarnings("hiding") PTermoLogica _termoLogica_)
    {
        // Constructor
        setTermoLogica(_termoLogica_);

    }

    @Override
    public Object clone()
    {
        return new ATermoExppLogica(
            cloneNode(this._termoLogica_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATermoExppLogica(this);
    }

    public PTermoLogica getTermoLogica()
    {
        return this._termoLogica_;
    }

    public void setTermoLogica(PTermoLogica node)
    {
        if(this._termoLogica_ != null)
        {
            this._termoLogica_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._termoLogica_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._termoLogica_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._termoLogica_ == child)
        {
            this._termoLogica_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._termoLogica_ == oldChild)
        {
            setTermoLogica((PTermoLogica) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
