/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AEnotLtermo extends PLtermo
{
    private PLtermo _ltermo_;
    private PLmult _lmult_;
    private PLfator _lfator_;

    public AEnotLtermo()
    {
        // Constructor
    }

    public AEnotLtermo(
        @SuppressWarnings("hiding") PLtermo _ltermo_,
        @SuppressWarnings("hiding") PLmult _lmult_,
        @SuppressWarnings("hiding") PLfator _lfator_)
    {
        // Constructor
        setLtermo(_ltermo_);

        setLmult(_lmult_);

        setLfator(_lfator_);

    }

    @Override
    public Object clone()
    {
        return new AEnotLtermo(
            cloneNode(this._ltermo_),
            cloneNode(this._lmult_),
            cloneNode(this._lfator_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEnotLtermo(this);
    }

    public PLtermo getLtermo()
    {
        return this._ltermo_;
    }

    public void setLtermo(PLtermo node)
    {
        if(this._ltermo_ != null)
        {
            this._ltermo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ltermo_ = node;
    }

    public PLmult getLmult()
    {
        return this._lmult_;
    }

    public void setLmult(PLmult node)
    {
        if(this._lmult_ != null)
        {
            this._lmult_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lmult_ = node;
    }

    public PLfator getLfator()
    {
        return this._lfator_;
    }

    public void setLfator(PLfator node)
    {
        if(this._lfator_ != null)
        {
            this._lfator_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lfator_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ltermo_)
            + toString(this._lmult_)
            + toString(this._lfator_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ltermo_ == child)
        {
            this._ltermo_ = null;
            return;
        }

        if(this._lmult_ == child)
        {
            this._lmult_ = null;
            return;
        }

        if(this._lfator_ == child)
        {
            this._lfator_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ltermo_ == oldChild)
        {
            setLtermo((PLtermo) newChild);
            return;
        }

        if(this._lmult_ == oldChild)
        {
            setLmult((PLmult) newChild);
            return;
        }

        if(this._lfator_ == oldChild)
        {
            setLfator((PLfator) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
