/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AExpLfator extends PLfator
{
    private PExp _exp_;
    private PParabool _parabool_;
    private POutraexp _outraexp_;

    public AExpLfator()
    {
        // Constructor
    }

    public AExpLfator(
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") PParabool _parabool_,
        @SuppressWarnings("hiding") POutraexp _outraexp_)
    {
        // Constructor
        setExp(_exp_);

        setParabool(_parabool_);

        setOutraexp(_outraexp_);

    }

    @Override
    public Object clone()
    {
        return new AExpLfator(
            cloneNode(this._exp_),
            cloneNode(this._parabool_),
            cloneNode(this._outraexp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpLfator(this);
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public PParabool getParabool()
    {
        return this._parabool_;
    }

    public void setParabool(PParabool node)
    {
        if(this._parabool_ != null)
        {
            this._parabool_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parabool_ = node;
    }

    public POutraexp getOutraexp()
    {
        return this._outraexp_;
    }

    public void setOutraexp(POutraexp node)
    {
        if(this._outraexp_ != null)
        {
            this._outraexp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._outraexp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exp_)
            + toString(this._parabool_)
            + toString(this._outraexp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._parabool_ == child)
        {
            this._parabool_ = null;
            return;
        }

        if(this._outraexp_ == child)
        {
            this._outraexp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._parabool_ == oldChild)
        {
            setParabool((PParabool) newChild);
            return;
        }

        if(this._outraexp_ == oldChild)
        {
            setOutraexp((POutraexp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
