/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AConjuntoDeclaracaoVariavel extends PDeclaracaoVariavel
{
    private PTipo _tipo_;
    private TDoispontos _doispontos_;
    private PDeclaracaoVariavelVirgula _declaracaoVariavelVirgula_;
    private PVariabilidade _variabilidade_;
    private PVariavel _variavel_;
    private TPontovirgula _pontovirgula_;

    public AConjuntoDeclaracaoVariavel()
    {
        // Constructor
    }

    public AConjuntoDeclaracaoVariavel(
        @SuppressWarnings("hiding") PTipo _tipo_,
        @SuppressWarnings("hiding") TDoispontos _doispontos_,
        @SuppressWarnings("hiding") PDeclaracaoVariavelVirgula _declaracaoVariavelVirgula_,
        @SuppressWarnings("hiding") PVariabilidade _variabilidade_,
        @SuppressWarnings("hiding") PVariavel _variavel_,
        @SuppressWarnings("hiding") TPontovirgula _pontovirgula_)
    {
        // Constructor
        setTipo(_tipo_);

        setDoispontos(_doispontos_);

        setDeclaracaoVariavelVirgula(_declaracaoVariavelVirgula_);

        setVariabilidade(_variabilidade_);

        setVariavel(_variavel_);

        setPontovirgula(_pontovirgula_);

    }

    @Override
    public Object clone()
    {
        return new AConjuntoDeclaracaoVariavel(
            cloneNode(this._tipo_),
            cloneNode(this._doispontos_),
            cloneNode(this._declaracaoVariavelVirgula_),
            cloneNode(this._variabilidade_),
            cloneNode(this._variavel_),
            cloneNode(this._pontovirgula_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAConjuntoDeclaracaoVariavel(this);
    }

    public PTipo getTipo()
    {
        return this._tipo_;
    }

    public void setTipo(PTipo node)
    {
        if(this._tipo_ != null)
        {
            this._tipo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tipo_ = node;
    }

    public TDoispontos getDoispontos()
    {
        return this._doispontos_;
    }

    public void setDoispontos(TDoispontos node)
    {
        if(this._doispontos_ != null)
        {
            this._doispontos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._doispontos_ = node;
    }

    public PDeclaracaoVariavelVirgula getDeclaracaoVariavelVirgula()
    {
        return this._declaracaoVariavelVirgula_;
    }

    public void setDeclaracaoVariavelVirgula(PDeclaracaoVariavelVirgula node)
    {
        if(this._declaracaoVariavelVirgula_ != null)
        {
            this._declaracaoVariavelVirgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._declaracaoVariavelVirgula_ = node;
    }

    public PVariabilidade getVariabilidade()
    {
        return this._variabilidade_;
    }

    public void setVariabilidade(PVariabilidade node)
    {
        if(this._variabilidade_ != null)
        {
            this._variabilidade_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._variabilidade_ = node;
    }

    public PVariavel getVariavel()
    {
        return this._variavel_;
    }

    public void setVariavel(PVariavel node)
    {
        if(this._variavel_ != null)
        {
            this._variavel_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._variavel_ = node;
    }

    public TPontovirgula getPontovirgula()
    {
        return this._pontovirgula_;
    }

    public void setPontovirgula(TPontovirgula node)
    {
        if(this._pontovirgula_ != null)
        {
            this._pontovirgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pontovirgula_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tipo_)
            + toString(this._doispontos_)
            + toString(this._declaracaoVariavelVirgula_)
            + toString(this._variabilidade_)
            + toString(this._variavel_)
            + toString(this._pontovirgula_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tipo_ == child)
        {
            this._tipo_ = null;
            return;
        }

        if(this._doispontos_ == child)
        {
            this._doispontos_ = null;
            return;
        }

        if(this._declaracaoVariavelVirgula_ == child)
        {
            this._declaracaoVariavelVirgula_ = null;
            return;
        }

        if(this._variabilidade_ == child)
        {
            this._variabilidade_ = null;
            return;
        }

        if(this._variavel_ == child)
        {
            this._variavel_ = null;
            return;
        }

        if(this._pontovirgula_ == child)
        {
            this._pontovirgula_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tipo_ == oldChild)
        {
            setTipo((PTipo) newChild);
            return;
        }

        if(this._doispontos_ == oldChild)
        {
            setDoispontos((TDoispontos) newChild);
            return;
        }

        if(this._declaracaoVariavelVirgula_ == oldChild)
        {
            setDeclaracaoVariavelVirgula((PDeclaracaoVariavelVirgula) newChild);
            return;
        }

        if(this._variabilidade_ == oldChild)
        {
            setVariabilidade((PVariabilidade) newChild);
            return;
        }

        if(this._variavel_ == oldChild)
        {
            setVariavel((PVariavel) newChild);
            return;
        }

        if(this._pontovirgula_ == oldChild)
        {
            setPontovirgula((TPontovirgula) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
