/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AParentesesLfator extends PLfator
{
    private TAbreparenteses _abreparenteses_;
    private PLexp _lexp_;
    private TFechaparenteses _fechaparenteses_;

    public AParentesesLfator()
    {
        // Constructor
    }

    public AParentesesLfator(
        @SuppressWarnings("hiding") TAbreparenteses _abreparenteses_,
        @SuppressWarnings("hiding") PLexp _lexp_,
        @SuppressWarnings("hiding") TFechaparenteses _fechaparenteses_)
    {
        // Constructor
        setAbreparenteses(_abreparenteses_);

        setLexp(_lexp_);

        setFechaparenteses(_fechaparenteses_);

    }

    @Override
    public Object clone()
    {
        return new AParentesesLfator(
            cloneNode(this._abreparenteses_),
            cloneNode(this._lexp_),
            cloneNode(this._fechaparenteses_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParentesesLfator(this);
    }

    public TAbreparenteses getAbreparenteses()
    {
        return this._abreparenteses_;
    }

    public void setAbreparenteses(TAbreparenteses node)
    {
        if(this._abreparenteses_ != null)
        {
            this._abreparenteses_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._abreparenteses_ = node;
    }

    public PLexp getLexp()
    {
        return this._lexp_;
    }

    public void setLexp(PLexp node)
    {
        if(this._lexp_ != null)
        {
            this._lexp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lexp_ = node;
    }

    public TFechaparenteses getFechaparenteses()
    {
        return this._fechaparenteses_;
    }

    public void setFechaparenteses(TFechaparenteses node)
    {
        if(this._fechaparenteses_ != null)
        {
            this._fechaparenteses_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fechaparenteses_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._abreparenteses_)
            + toString(this._lexp_)
            + toString(this._fechaparenteses_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._abreparenteses_ == child)
        {
            this._abreparenteses_ = null;
            return;
        }

        if(this._lexp_ == child)
        {
            this._lexp_ = null;
            return;
        }

        if(this._fechaparenteses_ == child)
        {
            this._fechaparenteses_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._abreparenteses_ == oldChild)
        {
            setAbreparenteses((TAbreparenteses) newChild);
            return;
        }

        if(this._lexp_ == oldChild)
        {
            setLexp((PLexp) newChild);
            return;
        }

        if(this._fechaparenteses_ == oldChild)
        {
            setFechaparenteses((TFechaparenteses) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
