/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ASuperDeclaracaoVariavel extends PSuperDeclaracaoVariavel
{
    private PSuperDeclaracaoVariavel _superDeclaracaoVariavel_;
    private PDeclaracaoVariavel _declaracaoVariavel_;

    public ASuperDeclaracaoVariavel()
    {
        // Constructor
    }

    public ASuperDeclaracaoVariavel(
        @SuppressWarnings("hiding") PSuperDeclaracaoVariavel _superDeclaracaoVariavel_,
        @SuppressWarnings("hiding") PDeclaracaoVariavel _declaracaoVariavel_)
    {
        // Constructor
        setSuperDeclaracaoVariavel(_superDeclaracaoVariavel_);

        setDeclaracaoVariavel(_declaracaoVariavel_);

    }

    @Override
    public Object clone()
    {
        return new ASuperDeclaracaoVariavel(
            cloneNode(this._superDeclaracaoVariavel_),
            cloneNode(this._declaracaoVariavel_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASuperDeclaracaoVariavel(this);
    }

    public PSuperDeclaracaoVariavel getSuperDeclaracaoVariavel()
    {
        return this._superDeclaracaoVariavel_;
    }

    public void setSuperDeclaracaoVariavel(PSuperDeclaracaoVariavel node)
    {
        if(this._superDeclaracaoVariavel_ != null)
        {
            this._superDeclaracaoVariavel_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._superDeclaracaoVariavel_ = node;
    }

    public PDeclaracaoVariavel getDeclaracaoVariavel()
    {
        return this._declaracaoVariavel_;
    }

    public void setDeclaracaoVariavel(PDeclaracaoVariavel node)
    {
        if(this._declaracaoVariavel_ != null)
        {
            this._declaracaoVariavel_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._declaracaoVariavel_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._superDeclaracaoVariavel_)
            + toString(this._declaracaoVariavel_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._superDeclaracaoVariavel_ == child)
        {
            this._superDeclaracaoVariavel_ = null;
            return;
        }

        if(this._declaracaoVariavel_ == child)
        {
            this._declaracaoVariavel_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._superDeclaracaoVariavel_ == oldChild)
        {
            setSuperDeclaracaoVariavel((PSuperDeclaracaoVariavel) newChild);
            return;
        }

        if(this._declaracaoVariavel_ == oldChild)
        {
            setDeclaracaoVariavel((PDeclaracaoVariavel) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
