/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AExpLogica extends PExpLogica
{
    private PExppLogica _exppLogica_;

    public AExpLogica()
    {
        // Constructor
    }

    public AExpLogica(
        @SuppressWarnings("hiding") PExppLogica _exppLogica_)
    {
        // Constructor
        setExppLogica(_exppLogica_);

    }

    @Override
    public Object clone()
    {
        return new AExpLogica(
            cloneNode(this._exppLogica_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpLogica(this);
    }

    public PExppLogica getExppLogica()
    {
        return this._exppLogica_;
    }

    public void setExppLogica(PExppLogica node)
    {
        if(this._exppLogica_ != null)
        {
            this._exppLogica_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exppLogica_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exppLogica_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exppLogica_ == child)
        {
            this._exppLogica_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exppLogica_ == oldChild)
        {
            setExppLogica((PExppLogica) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
