/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ASimplesLtermo extends PLtermo
{
    private PLfator _lfator_;

    public ASimplesLtermo()
    {
        // Constructor
    }

    public ASimplesLtermo(
        @SuppressWarnings("hiding") PLfator _lfator_)
    {
        // Constructor
        setLfator(_lfator_);

    }

    @Override
    public Object clone()
    {
        return new ASimplesLtermo(
            cloneNode(this._lfator_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimplesLtermo(this);
    }

    public PLfator getLfator()
    {
        return this._lfator_;
    }

    public void setLfator(PLfator node)
    {
        if(this._lfator_ != null)
        {
            this._lfator_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lfator_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._lfator_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._lfator_ == child)
        {
            this._lfator_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._lfator_ == oldChild)
        {
            setLfator((PLfator) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
