/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ACorpoPrograma extends PCorpoPrograma
{
    private PCorpoPrograma _corpoPrograma_;
    private TIdentificador _identificador_;

    public ACorpoPrograma()
    {
        // Constructor
    }

    public ACorpoPrograma(
        @SuppressWarnings("hiding") PCorpoPrograma _corpoPrograma_,
        @SuppressWarnings("hiding") TIdentificador _identificador_)
    {
        // Constructor
        setCorpoPrograma(_corpoPrograma_);

        setIdentificador(_identificador_);

    }

    @Override
    public Object clone()
    {
        return new ACorpoPrograma(
            cloneNode(this._corpoPrograma_),
            cloneNode(this._identificador_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACorpoPrograma(this);
    }

    public PCorpoPrograma getCorpoPrograma()
    {
        return this._corpoPrograma_;
    }

    public void setCorpoPrograma(PCorpoPrograma node)
    {
        if(this._corpoPrograma_ != null)
        {
            this._corpoPrograma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._corpoPrograma_ = node;
    }

    public TIdentificador getIdentificador()
    {
        return this._identificador_;
    }

    public void setIdentificador(TIdentificador node)
    {
        if(this._identificador_ != null)
        {
            this._identificador_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identificador_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._corpoPrograma_)
            + toString(this._identificador_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._corpoPrograma_ == child)
        {
            this._corpoPrograma_ = null;
            return;
        }

        if(this._identificador_ == child)
        {
            this._identificador_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._corpoPrograma_ == oldChild)
        {
            setCorpoPrograma((PCorpoPrograma) newChild);
            return;
        }

        if(this._identificador_ == oldChild)
        {
            setIdentificador((TIdentificador) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
